### ISSUE TITLE
Download only 30 video

### ISSUE THREAD

**Issue by Reamasa** [charmparticle/tiktokget#1]
What the problem? I'm can only download 30 videos in a user profile. Thanks

**Comment by charmparticle** [comment]
Do you get any error messages? The script should download all of a user's videos -- it does for me.

My suspicion is something about driver.execute_script isn't working properly on your system for some reason.

**Comment by Reamasa** [comment]
> Do you get any error messages? The script should download all of a user's videos -- it does for me.
> 
> My suspicion is something about driver.execute_script isn't working properly on your system for some reason.

Thanks for reply! I don't got any error messages. If it work well for you I think maybe I'm wrong configure something. 
I don't know what wrong but it start download video start from: 030_ ... till 001_.

**Comment by charmparticle** [comment]
If you get the time, please show me a copy of your geckodriver.log - it would be in the same folder you invoked tiktokget in. Copy it to your github as a gist or maybe use pastebin.com and send me the link. There might be some clues in there.

**Comment by Reamasa** [comment]
> If you get the time, please show me a copy of your geckodriver.log - it would be in the same folder you invoked tiktokget in. Copy it to your github as a gist or maybe use pastebin.com and send me the link. There might be some clues in there.

This the error log: https://pastebin.com/r7ckFS6W . You can check . Thanks.

**Comment by charmparticle** [comment]
I guess I should update my documentation to remove Windows support. Sorry about that.

**Comment by Reamasa** [comment]
> 

:( Thanks for your time.
