### ISSUE TITLE
I use this and get error

### ISSUE THREAD

**Issue by carlosecv** [charmparticle/tiktokget#15]
Installed:
sudo  pip3 install tiktokget

Run:
tiktokget -l https://www.tiktok.com/@taichi.zidong
/usr/local/bin/tiktokget:85: DeprecationWarning: headless property is deprecated, instead use add_argument('-headless')
  opts.headless = True
Specific exercise Improve symptoms, daily fully- body exercise remove root causes..mp4
Downloading...
ERROR: [tiktok:user] taichi.zidong: taichi.zidong: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

 yt-dlp -U
Available version: stable@2023.06.22, Current version: stable@2023.06.22
yt-dlp is up to date (stable@2023.06.22)

**Comment by charmparticle** [comment]
I have completely revamped this utility. It's nothing more than a shellscript wrapper around yt-dlp now.
