### ISSUE TITLE
Undeclared dependency on sarge

### ISSUE THREAD

**Issue by tomwhoiscontrary** [charmparticle/tiktokget#16]
After a fresh install in a venv:

```
$ tiktokget prozd_tiktok
Traceback (most recent call last):
  File "/home/tomwhoiscontrary/bin/tiktokget", line 8, in <module>
    from sarge import get_stdout
ModuleNotFoundError: No module named 'sarge'
```

After doing `pip install --upgrade sarge`, the scripts seems to run fine.

The wheel metadata has requires for yt-dlp, requests, and selenium, so i suspect it just needs one for sarge as well.

**Comment by charmparticle** [comment]
Thanks for calling this to my attention -- I updated the pip package just now.
