### ISSUE TITLE
Downloads only 30 videos

### ISSUE THREAD

**Issue by hanssonrickard** [charmparticle/tiktokget#2]
Hi.
I can see that it has already been discusse,d but that issue was closed with you saying that you should remove windows support.
I am running your script in macos and the same happens for me, regardless of which account i try to download all videos from, only 30 videos are downloaded, counting down from 30 -> 01 (how it names them).

Could it be that Gecko Driver only downloads the first videos that are shown and some kind of "continous scrolling" to load more/all videos are needed to load the complete list?

There are no errors when downloading, but the behavior is the same each time and what makes it even more consistent is that it always starts downloading the video named 30 first, so it is pretty intentional.

**Comment by charmparticle** [comment]
>Could it be that Gecko Driver only downloads the first videos that are shown and some kind of "continous scrolling" to load more/all videos are needed to load the complete list?

This is correct. By default, when you go to a user's tiktok page, only 30 videos are displayed. To get the rest to display, the browser needs to scroll to the bottom of the window. I have some javascript code I execute in the script that is supposed to do exactly that. Maybe python has updated the driver.execute_script() function in a recent version of the selenium library? Maybe try using pyenv to try using an older version of python?

**Comment by hanssonrickard** [comment]
The problem seems to be that when using selenium (visible if you let it open a brownser (not headless) is that it gives a puzzle captcha that needs to be perform before infinite scroll can be used in tiktok.
So basically they have added a way to stop scraping their site.
There seems to be code out there that is trying to solve the captcha automatically via python code.

But this is the reason what i can see/find out.

**Comment by charmparticle** [comment]
Thank you for finding the root cause.
