### ISSUE TITLE
Download liked|bookmarked videos

### ISSUE THREAD

**Issue by xxzozaxx** [charmparticle/tiktokget#4]
I want to donwload all the videos I liked or bookmarked on my account. Hope this gonna be easy to implement

**Comment by dfjeiwn** [comment]
If you want to download TikTok videos on your desktop or mobile devices, you can use StreamFab YouTube Downloader. Despite being named [YouTube video downloader](https://streamfab.com/youtube-video-downloader.htm), it comes with many features that not only can [download YouTube videos](https://streamfab.com/how-to-download-youtube-videos), but also videos from 1000+ other websites, including TiKTok.

**Comment by xxzozaxx** [comment]
Thanks for your replay, ur recommended seem not to have a Linux version,
anyway I found a hacky way to make it works with yt-dlp (a software to
download videos from almost any website)

Thanks for your time

A. K. ::= David Gabriel
